export { DefesaHero } from "./defesa-hero";
export { DefesaIdentificacao } from "./defesa-identificacao";
export { DefesaSolucao } from "./defesa-solucao";
export { DefesaAutoridade } from "./defesa-autoridade";
export { DefesaProvas } from "./defesa-provas";
export { DefesaFaq } from "./defesa-faq";
export { DefesaFooter } from "./defesa-footer";
export { DefesaEducacional } from "./defesa-educacional";
export { DefesaInstagram } from "./defesa-instagram";
